// Pool de Perguntas para o Teste de Afinidade (64 Perguntas - Bilingue 💖)
const coupleQuestionsPool = {
  pt: [
    { id: 1, text: "Quem tem mais chance de se machucar?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 2, text: "Quem tem mais chance de pegar uma queimadura de sol?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 3, text: "Quem tem mais chance de se perder?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 4, text: "Quem tem mais chance de pedir informação na rua?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 5, text: "Quem tem mais chance de acordar de mau humor?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 6, text: "Quem tem mais chance de começar uma briga?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 7, text: "Quem tem mais chance de encerrar uma discussão?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 8, text: "Quem tem mais chance de estourar o limite do cartão de crédito?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 9, text: "Quem tem mais chance de economizar todo o dinheiro?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 10, text: "Quem tem mais chance de perder as chaves ou a carteira?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 11, text: "Quem tem mais chance de fazer do chão do quarto o seu cesto de roupa suja?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 12, text: "Quem tem mais chance de roubar alguém?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 13, text: "Quem tem mais chance de estragar as roupas ao lavar?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 14, text: "Quem tem mais chance de dar uma desculpa para escapar de algo que não quer fazer?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 15, text: "Quem tem mais chance de chorar vendo filme?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 16, text: "Quem tem mais chance de planejar uma viagem de última hora?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 17, text: "Quem tem mais chance de dizer \"Eu te amo\" primeiro no meio de uma briga?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 18, text: "Quem tem mais chance de planejar uma surpresa em segredo?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 19, text: "Quem tem mais chance de puxar assunto com um desconhecido?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 20, text: "Quem tem mais chance de sair do assunto durante uma conversa séria?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 21, text: "Quem tem mais chance de ver um significado profundo em algo pequeno?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 22, text: "Quem tem mais chance de lembrar dos mínimos detalhes?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 23, text: "Quem tem mais chance de desenterrar uma discussão antiga?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 24, text: "Quem tem mais chance de escrever sobre o relacionamento em um diário secreto?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 25, text: "Quem tem mais chance de tentar curar os próprios traumas sozinho?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 26, text: "Quem tem mais chance de rir em um momento totalmente errado?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 27, text: "Quem tem mais chance de falar algo inapropriado na frente dos pais do outro?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 28, text: "Quem tem mais chance de esquecer o que estava falando no meio da frase?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 29, text: "Quem tem mais chance de rir até chorar da própria piada?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 30, text: "Quem tem mais chance de comer sobremesa no café da manhã?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 31, text: "Quem tem mais chance de dormir no meio do filme (e negar depois)?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 32, text: "Quem tem mais chance de pedir seis acompanhamentos em vez de um prato principal?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 33, text: "Quem tem mais chance de esquecer onde estacionou o carro?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 34, text: "Quem tem mais chance de ficar excitado no meio de uma discussão?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 35, text: "Quem tem mais chance de querer se mudar para um lugar novo para recomeçar?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 36, text: "Quem tem mais chance de sugerir um detox digital?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 37, text: "Quem tem mais chance de comprar pijamas combinando para o casal?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 38, text: "Quem tem mais chance de maratonar uma série inteira sem esperar pelo parceiro?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 39, text: "Quem tem mais chance de contar a mesma história de novo e de novo?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 40, text: "Quem tem mais chance de ficar irritado de fome primeiro?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 41, text: "Quem tem mais chance de esquecer pelo que estavam brigando cinco minutos depois?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 42, text: "Quem tem mais chance de ficar estranhamente competitivo em jogos?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 43, text: "Quem tem mais chance de pedir \"só um pedacinho\" e comer metade da sua comida?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 44, text: "Quem tem mais chance de tentar consertar algo em casa sozinho e piorar a situação?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 45, text: "Quem tem mais chance de voluntariar vocês dois para algo sem perguntar antes?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 46, text: "Quem tem mais chance de aceitar ir no assento do meio no avião?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 47, text: "Quem tem mais chance de brigar pela temperatura do ar-condicionado?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 48, text: "Quem tem mais chance de querer uma comemoração de fim de ano enorme e cheia de gente?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 49, text: "Quem tem mais chance de ganhar uma briga fazendo o outro rir?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 50, text: "Quem tem mais chance de falar durante o filme inteiro?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 51, text: "Quem tem mais chance de virar melhor amigo do motorista de Uber?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 52, text: "Quem tem mais chance de ficar sem combustível porque \"achou que ia dar\"?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 53, text: "Quem tem mais chance de apertar o soneca cinco vezes seguidas?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 54, text: "Quem tem mais chance de manter a calma durante uma emergência?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 55, text: "Quem tem mais chance de entrar em um show ou evento sem ingresso?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 56, text: "Quem tem mais chance de fazer xixi no banho?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 57, text: "Quem tem mais chance de morrer primeiro em um filme de terror?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 58, text: "Quem tem mais chance de trazer provas (\"prints\") no meio de uma discussão?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 59, text: "Quem tem mais chance de ficar uma semana sem tomar banho?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 60, text: "Quem tem mais chance de pedir para devolver a comida no restaurante?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 61, text: "Quem tem mais chance de sobreviver a uma abdução alienígena?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 62, text: "Quem tem mais chance de esquecer o desodorante?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 63, text: "Quem tem mais chance de se assustar com um objeto inanimado?", options: ["Eu", "Você", "Nós dois", "Nenhum"] },
    { id: 64, text: "Quem tem mais chance de ter 30 abas abertas no navegador o tempo todo?", options: ["Eu", "Você", "Nós dois", "Nenhum"] }
  ],
  en: [
    { id: 1, text: "Who is more likely to get injured?", options: ["Me", "You", "Both", "None"] },
    { id: 2, text: "Who is more likely to get sunburn?", options: ["Me", "You", "Both", "None"] },
    { id: 3, text: "Who is more likely to get lost?", options: ["Me", "You", "Both", "None"] },
    { id: 4, text: "Who is more likely to ask for directions?", options: ["Me", "You", "Both", "None"] },
    { id: 5, text: "Who is more likely to wake up grumpy?", options: ["Me", "You", "Both", "None"] },
    { id: 6, text: "Who is more likely to start an argument?", options: ["Me", "You", "Both", "None"] },
    { id: 7, text: "Who is more likely to finish an argument?", options: ["Me", "You", "Both", "None"] },
    { id: 8, text: "Who is more likely to max out their credit card?", options: ["Me", "You", "Both", "None"] },
    { id: 9, text: "Who is more likely to save all their money?", options: ["Me", "You", "Both", "None"] },
    { id: 10, text: "Who is more likely to lose their keys or wallet?", options: ["Me", "You", "Both", "None"] },
    { id: 11, text: "Who is more likely to make the bedroom floor their personal laundry basket?", options: ["Me", "You", "Both", "None"] },
    { id: 12, text: "Who is more likely to rob someone?", options: ["Me", "You", "Both", "None"] },
    { id: 13, text: "Who is more likely to destroy clothing doing the laundry?", options: ["Me", "You", "Both", "None"] },
    { id: 14, text: "Who is more likely to get out of something they don't want to do?", options: ["Me", "You", "Both", "None"] },
    { id: 15, text: "Who's most likely to cry during a movie?", options: ["Me", "You", "Both", "None"] },
    { id: 16, text: "Who's most likely to book a last-minute trip?", options: ["Me", "You", "Both", "None"] },
    { id: 17, text: "Who's most likely to say \"I love you\" first in an argument?", options: ["Me", "You", "Both", "None"] },
    { id: 18, text: "Who's most likely to secretly plan a surprise?", options: ["Me", "You", "Both", "None"] },
    { id: 19, text: "Who's most likely to strike up a convo with a stranger?", options: ["Me", "You", "Both", "None"] },
    { id: 20, text: "Who's most likely to go off-script during a serious talk?", options: ["Me", "You", "Both", "None"] },
    { id: 21, text: "Who's most likely to see the deeper meaning in something small?", options: ["Me", "You", "Both", "None"] },
    { id: 22, text: "Who's most likely to remember the little things?", options: ["Me", "You", "Both", "None"] },
    { id: 23, text: "Who's most likely to bring up an old disagreement?", options: ["Me", "You", "Both", "None"] },
    { id: 24, text: "Who's most likely to secretly journal about the relationship?", options: ["Me", "You", "Both", "None"] },
    { id: 25, text: "Who's most likely to try healing work on their own?", options: ["Me", "You", "Both", "None"] },
    { id: 26, text: "Who's most likely to laugh at the wrong moment?", options: ["Me", "You", "Both", "None"] },
    { id: 27, text: "Who's the most likely to say something inappropriate in front of the other's parents?", options: ["Me", "You", "Both", "None"] },
    { id: 28, text: "Who's most likely to forget what they were saying mid-sentence?", options: ["Me", "You", "Both", "None"] },
    { id: 29, text: "Who's most likely to cry-laugh at their own joke?", options: ["Me", "You", "Both", "None"] },
    { id: 30, text: "Who's most likely to eat dessert for breakfast?", options: ["Me", "You", "Both", "None"] },
    { id: 31, text: "Who's most likely to fall asleep mid-movie (and deny it)?", options: ["Me", "You", "Both", "None"] },
    { id: 32, text: "Who's most likely to order six sides instead of a main dish?", options: ["Me", "You", "Both", "None"] },
    { id: 33, text: "Who's most likely to forget where they parked their car?", options: ["Me", "You", "Both", "None"] },
    { id: 34, text: "Who's most likely to get turned on mid-argument?", options: ["Me", "You", "Both", "None"] },
    { id: 35, text: "Who's most likely to want to move to a new place for a fresh start?", options: ["Me", "You", "Both", "None"] },
    { id: 36, text: "Who's most likely to want a digital detox?", options: ["Me", "You", "Both", "None"] },
    { id: 37, text: "Who is most likely to buy matching pajama sets?", options: ["Me", "You", "Both", "None"] },
    { id: 38, text: "Who is most likely to binge an entire series without waiting for their partner?", options: ["Me", "You", "Both", "None"] },
    { id: 39, text: "Who is most likely to retell a story over and over?", options: ["Me", "You", "Both", "None"] },
    { id: 40, text: "Who is most likely to get hangry first?", options: ["Me", "You", "Both", "None"] },
    { id: 41, text: "Who is most likely to forget what they argued about five minutes later?", options: ["Me", "You", "Both", "None"] },
    { id: 42, text: "Who is most likely to get weirdly competitive over games?", options: ["Me", "You", "Both", "None"] },
    { id: 43, text: "Who is most likely to take “just a bite” and eat half your food?", options: ["Me", "You", "Both", "None"] },
    { id: 44, text: "Who is most likely to try to DIY home repairs and make it worse?", options: ["Me", "You", "Both", "None"] },
    { id: 45, text: "Who is most likely to volunteer the two of you for something without asking first?", options: ["Me", "You", "Both", "None"] },
    { id: 46, text: "Who is most likely to take the middle seat on an airplane?", options: ["Me", "You", "Both", "None"] },
    { id: 47, text: "Who is most likely to pick a fight over thermostat settings?", options: ["Me", "You", "Both", "None"] },
    { id: 48, text: "Who is most likely to want a big, elaborate family holiday celebration?", options: ["Me", "You", "Both", "None"] },
    { id: 49, text: "Who is most likely to win an argument by making the other laugh?", options: ["Me", "You", "Both", "None"] },
    { id: 50, text: "Who is most likely to talk through an entire movie?", options: ["Me", "You", "Both", "None"] },
    { id: 51, text: "Who is most likely to befriend your Uber driver?", options: ["Me", "You", "Both", "None"] },
    { id: 52, text: "Who is most likely to run out of gas because they “thought it would last”?", options: ["Me", "You", "Both", "None"] },
    { id: 53, text: "Who is most likely to snooze their alarm five times in a row?", options: ["Me", "You", "Both", "None"] },
    { id: 54, text: "Who is most likely to stay calm during an emergency?", options: ["Me", "You", "Both", "None"] },
    { id: 55, text: "Who is most likely to sneak into a concert or event without a ticket?", options: ["Me", "You", "Both", "None"] },
    { id: 56, text: "Who is most likely to pee in the shower?", options: ["Me", "You", "Both", "None"] },
    { id: 57, text: "Who is most likely to die first in a horror film?", options: ["Me", "You", "Both", "None"] },
    { id: 58, text: "Who is most likely to expose receipts during an argument?", options: ["Me", "You", "Both", "None"] },
    { id: 59, text: "Who is most likely to go a week without a shower?", options: ["Me", "You", "Both", "None"] },
    { id: 60, text: "Who is most likely to send their food back at a restaurant?", options: ["Me", "You", "Both", "None"] },
    { id: 61, text: "Who is most likely to survive an alien abduction?", options: ["Me", "You", "Both", "None"] },
    { id: 62, text: "Who is most likely to forget deodorant?", options: ["Me", "You", "Both", "None"] },
    { id: 63, text: "Who is most likely to get scared by an inanimate object?", options: ["Me", "You", "Both", "None"] },
    { id: 64, text: "Who is most likely to have 30 tabs open at all times?", options: ["Me", "You", "Both", "None"] }
  ]
};
